delete from SHOPPING_EVENTS where product_id = 'product_id';

CREATE OR REPLACE TABLE SHOPPING_EVENTS_TRANFORMED AS
SELECT
    TO_TIMESTAMP_NTZ(REPLACE(EVENT_TIME,' UTC')) AS EVENT_TIME,
    EVENT_TYPE,
    PRODUCT_ID::int AS PRODUCT_ID,
    CATEGORY_ID::BIGINT AS CATEGORY_ID,
    STRTOK(CATEGORY_CODE, '.', 1) as CATEGORY1,
    STRTOK(CATEGORY_CODE, '.', 2) as CATEGORY2,
    STRTOK(CATEGORY_CODE, '.', 3) as CATEGORY3,
    BRAND,
    PRICE::FLOAT AS PRICE,
    USER_ID::BIGINT AS USER_ID,
    USER_SESSION
FROM SHOPPING_EVENTS