SELECT
    EVENT_TYPE,
    PRODUCT_ID::int AS PRODUCT_ID,
    CATEGORY_ID::BIGINT AS CATEGORY_ID,
    BRAND,
    count(distinct USER_ID::BIGINT) AS USER_ID_count
FROM SHOPPING_EVENTS group by 1, 2, 3, 4;